# Generated by Django 3.2.19 on 2023-07-25 02:45

from django.db import migrations, models
import message.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text='Команда может быть только латинскими буквами', max_length=150, unique=True, validators=[message.validators.command_validator], verbose_name='Команда бота')),
                ('function', models.TextField(choices=[('wake_up', 'команда для старта'), ('help', 'команда для вызова помощи'), ('get_news', 'команда для новостей'), ('get_weather', 'команда для погоды')], max_length=150, unique=True, verbose_name='Описание действий бота')),
                ('message', models.TextField(verbose_name='Сообщение, которое отправляется пользователю')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('command',),
            },
        ),
        migrations.CreateModel(
            name='HistoryOfMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.CharField(max_length=150, verbose_name='Пользователь телеграмм')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
            ],
            options={
                'verbose_name': 'История сообщений',
                'verbose_name_plural': 'История сообщений',
                'ordering': ('-pub_date',),
            },
        ),
    ]
