# Generated by Django 3.2.19 on 2023-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(max_length=150, unique=True, verbose_name='Команда бота')),
                ('function', models.TextField(choices=[('команда для старта', 'wake_up'), ('команда для вызова помощи', 'help'), ('команда для новостей', 'get_news'), ('команда для погоды', 'get_weather')], max_length=150, unique=True, verbose_name='Описание действий бота')),
                ('message', models.TextField(verbose_name='Сообщение, которое отправляется пользователю')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('command',),
            },
        ),
        migrations.CreateModel(
            name='HistoryOfMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Имя пользователя в телеграмме')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
            ],
            options={
                'verbose_name': 'История сообщений',
                'ordering': ('-pub_date',),
            },
        ),
    ]
