# Generated by Django 3.2.19 on 2023-07-24 11:45

from django.db import migrations, models
import message.validators


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='command',
            field=models.TextField(help_text='Команда может быть только латинскими буквами', max_length=150, unique=True, validators=[message.validators.command_validator], verbose_name='Команда бота'),
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='function',
            field=models.TextField(choices=[('wake_up', 'команда для старта'), ('help', 'команда для вызова помощи'), ('get_news', 'команда для новостей'), ('get_weather', 'команда для погоды')], max_length=150, unique=True, verbose_name='Описание действий бота'),
        ),
        migrations.AlterField(
            model_name='historyofmessage',
            name='user',
            field=models.CharField(max_length=150, verbose_name='ID чата с пользователем в телеграмме'),
        ),
    ]
