# Generated by Django 3.2.19 on 2023-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyofmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='message/images/', verbose_name='Фото'),
        ),
    ]
